# Generated by Django 5.0.6 on 2024-06-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0002_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lead_app.master')),
                ('district_name', models.CharField(max_length=900)),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.state')),
            ],
            bases=('lead_app.master',),
        ),
    ]
