# Generated by Django 5.0.6 on 2024-06-06 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0003_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lead_app.master')),
                ('highest_qualification', models.CharField(max_length=200)),
            ],
            bases=('lead_app.master',),
        ),
    ]
