# Generated by Django 4.2.6 on 2024-06-06 07:22

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0006_follow_up_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lead_app.master')),
                ('branch_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('branch_code', models.CharField(max_length=200)),
                ('district_name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state_name', chained_model_field='State', on_delete=django.db.models.deletion.CASCADE, to='lead_app.district')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.state')),
            ],
            bases=('lead_app.master',),
        ),
    ]
