# Generated by Django 4.2.6 on 2024-06-06 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead_app', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oneteam_Batch',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lead_app.master')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_year', models.PositiveIntegerField(editable=False, null=True)),
                ('batch_name', models.CharField(editable=False, max_length=100, unique=True)),
                ('batch', models.CharField(blank=True, max_length=255)),
                ('branch_name', models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='lead_app.branch')),
                ('course_name', models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='lead_app.course')),
                ('trainer', models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL, verbose_name='Trainer')),
            ],
            bases=('lead_app.master',),
        ),
    ]
