# Generated by Django 4.2.6 on 2024-06-06 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead_app', '0010_alter_oneteam_batch_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneteam_batch',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL, verbose_name='Trainer'),
        ),
    ]
