# Generated by Django 4.2.6 on 2024-06-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0012_rename_oneteam_batch_c_oneteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_oneteam',
            name='branch_name',
        ),
    ]
