# Generated by Django 4.2.6 on 2024-06-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead_app', '0011_alter_oneteam_batch_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lead_app.master')),
                ('name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=20)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('reg_no', models.CharField(max_length=20)),
                ('branches', models.CharField(max_length=200)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.course')),
                ('enquirysource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.enquery_source')),
                ('qualification_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.qualification')),
            ],
            bases=('lead_app.master',),
        ),
    ]
